apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chat2md
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: default
  path: "./k8s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: chat2md
